# Generated by Django 5.2.1 on 2025-06-26 18:54

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

'''
Source: https://wordpress.org/documentation/article/roles-and-capabilities/

Summary of Roles

1. Super Admin - somebody with access to the site network administration features and all other features. See the Create a Network article.
2. Administrator (slug: 'administrator') - somebody who has access to all the administration features within a single site.
3. Editor (slug: 'editor') - somebody who can publish and manage posts including the posts of other users.
4. Author  (slug: 'author')  - somebody who can publish and manage their own posts.
5. Contributor (slug: 'contributor') - somebody who can write and manage their own posts but cannot publish them.
6. Subscriber (slug: 'subscriber') - somebody who can only manage their profile.
'''


def create_editor_group(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    content_type = ContentType.objects.get_for_model(Post)
    Editor, _ = Group.objects.get_or_create(name='Editor')

    permissions = Permission.objects.filter(content_type=content_type)
    Editor.permissions.set(permissions)


def create_author_group(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    content_type = ContentType.objects.get_for_model(Post)
    Author, _ = Group.objects.get_or_create(name='Author')

    excluded_permissions_codenames = [
        'edit_others_posts', 'delete_others_posts'
    ]
    permissions = Permission.objects.filter(content_type=content_type).exclude(
        codename__in=excluded_permissions_codenames)

    Author.permissions.set(permissions)


def create_contributor_group(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    content_type = ContentType.objects.get_for_model(Post)
    Contributor, _ = Group.objects.get_or_create(name='Contributor')

    excluded_permissions_codenames = [
        'publish_posts', 'edit_published_posts', 'delete_published_posts',
        'edit_others_posts', 'delete_others_posts'
    ]
    permissions = Permission.objects.filter(content_type=content_type).exclude(
        codename__in=excluded_permissions_codenames)

    Contributor.permissions.set(permissions)


def create_subscriber_group(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    content_type = ContentType.objects.get_for_model(Post)
    Subscriber, _ = Group.objects.get_or_create(name='Subscriber')

    excluded_permissions_codenames = [
        'edit_posts', 'delete_posts',
        'publish_posts', 'edit_published_posts', 'delete_published_posts',
        'edit_others_posts', 'delete_others_posts'
    ]
    permissions = Permission.objects.filter(content_type=content_type).exclude(
        codename__in=excluded_permissions_codenames)

    Subscriber.permissions.set(permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_editor_group),
        migrations.RunPython(create_author_group),
        migrations.RunPython(create_contributor_group),
        migrations.RunPython(create_subscriber_group),
    ]
