# Generated by Django 5.2.1 on 2025-06-29 20:04

import django.db.models.deletion
import martor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250627_0254'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('read', 'Can view posts'), ('delete_posts', 'Can delete own posts'), ('edit_posts', 'Can edit own posts'), ('delete_published_posts', 'Can delete own published posts'), ('edit_published_posts',
                                     'Can edit own published posts'), ('publish_posts', 'Can publish posts'), ('delete_others_posts', 'Can delete posts created by other users'), ('edit_others_posts', 'Can edit posts created by other users'))},
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', martor.models.MartorField()),
                ('birth_date', models.DateField()),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
