# Generated by Django 5.2.1 on 2025-07-01 16:42

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=20)),
                ('about_me', martor.models.MartorField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogsettings')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.socialplatform')),
            ],
            options={
                'unique_together': {('blog', 'platform')},
            },
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='social_links',
            field=models.ManyToManyField(through='blog.SocialLink', to='blog.socialplatform'),
        ),
    ]
