# Generated by Django 5.2.1 on 2025-07-01 17:20

import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogsettings_socialplatform_sociallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='bio',
            field=martor.models.MartorField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/profile_images/'),
        ),
    ]
