# Generated by Django 5.2.1 on 2025-06-21 21:18

import autoslug.fields
from django.db import migrations
from book.models import Author


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True,
                                                editable=False, populate_from='name'),
        ),
    ]
