# Generated by Django 5.2.1 on 2025-06-21 21:26

import autoslug.fields
from django.db import migrations
from django.utils.text import slugify


def update_author_slug(apps, schema_editor):
    Author = apps.get_model("book", "Author")

    for instance in Author.objects.all():
        if not instance.slug:
            instance.slug = slugify(instance.name)
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_slug'),
    ]

    operations = [
        migrations.RunPython(update_author_slug),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name', unique=True),
        ),
    ]
