# Generated by Django 5.2.1 on 2025-06-20 20:54

import autoslug.fields
import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', martor.models.MartorField(blank=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('voters', models.PositiveIntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('booklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.booklist')),
            ],
            options={
                'unique_together': {('booklist', 'book')},
            },
        ),
        migrations.AddField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(related_name='booklists', through='list.BookListEntry', to='book.book'),
        ),
    ]
